### ISSUE TITLE
Game stopped with fatal error

### ISSUE THREAD

**Issue by Kiritow** [Relik77/factorio_computer_core#10]
Game Version: 0.16.36-2
Computer Core 1.3.11
In sandbox mode, if **All tech please** is pressed, the following error occurs:
```
Error while running event computer_core::on_gui_click (ID 1)
__computer_core__/logic/computer.lua:69: attempt to index local 'entity' (a nil value)
```
If **OK** is clicked, then the game returns to home page immediately.
Also Control+Left Click does not open any GUI.

**Comment by Relik77** [comment]
Hi,

I had not tested the sandbox mode yet and did not know that with this mode we were playing without a character. I will look to disable the button of the personal computer in this case, because it may cause too much edge effects :-/
(I'll try later to reactivate it)

To open a GUI on a computer, it must be powered. If so, check your keyboard shortcuts (it can be set in the shorcut menu > options > mods)

**Comment by Kiritow** [comment]
According to more tests, I found if no computer window is opened and the button is pressed, then the game will get crashed. Else it works fine. Could you move the close button to the opened console?
As for shortcuts, I have checked it in settings tab. The default value is `Ctrl+Unknown`. After setting it to `Ctrl+Left Click`, everything is ok now.
By the way, this is really an amazing mod !!! I love it very much!

**Comment by Relik77** [comment]
v1.3.12 available, normally the button should no longer make the game bug and continue to normally close the window if there is one open.

Note :
In normal play, it also allows to open a computer related to the character of the player.
It is also possible to close the window in several ways in addition to the button:
- "exit" command
- right click on the top of the open window (that's what I prefer to use)
